### ISSUE TITLE
[🐞] npm run build.server not working as expected

### ISSUE THREAD

**Issue by mapp113** [QwikDev/qwik#8031]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I created a new app with `npm create qwik@latest`
Add static adapter `npm run qwik add static`
Add route `apple` in `src`

<img width="371" height="168" alt="Image" src="https://github.com/user-attachments/assets/c823b015-48e4-44ad-af01-34c5385f6f93" />

Then run `npm run build.server`
Folder `apple` is missing in `dist`

<img width="1031" height="367" alt="Image" src="https://github.com/user-attachments/assets/97b6084a-09a9-4f9e-9cda-1397827cf6fe" />

This behavior happens most of the time i build.

### Reproduction

https://github.com/mapp113/qwik-app

### Steps to reproduce

run `npm run build.server`

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 5.90 GB / 15.78 GB
  Binaries:
    Node: 22.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (140.0.3485.54)
    Internet Explorer: 11.0.26100.1882
```

### Additional Information

When i run `npm run build`

The console give me `Error: Command failed with exit code 3221226356: npm run build.server`

<img width="1482" height="762" alt="Image" src="https://github.com/user-attachments/assets/c92ead7a-9765-4033-92a2-57a7c982420b" />

**Comment by maiieul** [comment]
@wmertens @Varixo @gioboa this is the same error we've been seeing on the failing E2Es on windows.

mapp113 here is running the commands on Windows 11 10.0.26100.



@mapp113 FYI, it should be the build.client that would be containing your `apple` route.

**Comment by maiieul** [comment]
@mapp113 could you try with v2 and report back? 🙏

**Comment by wmertens** [comment]
@mapp113 actually it would be the nightly build for V2 to check. 

Can you perhaps also make sure that all your dependencies (vite etc) are at the latest?

**Comment by maiieul** [comment]
(you might need to manually add rollup@latest to your package.json)

**Comment by mapp113** [comment]
@wmertens @maiieul thank for reply

I migrate the project to v2 and update all dependencies to latest. The build is still fail😢

<details>
<summary>This is my console look like</summary>

```
build.server
qwik check-client src dist && vite build -c adapters/static/vite.config.ts


vite v7.1.9 building SSR bundle for production...
transforming (1) @qwik-router-config
==========
Could not read Qwik client manifest D:\Project\qwik-app\dist\q-manifest.json.
Make sure you provide it to the SSR renderer via the `manifest` argument, or define it in `globalThis.__QWIK_MANIFEST__` before the server bundle is loaded, or embed it in the server bundle by replacing `globalThis.__QWIK_MANIFEST__`.
Without the manifest, the SSR renderer will not be able to generate event handlers.
(Error: ENOENT: no such file or directory, open 'D:\Project\qwik-app\dist\q-manifest.json')
==========

✓ 14 modules transformed.
server/build/q-D8xXZngC.js       0.04 kB
server/@qwik-router-config.js    0.30 kB
server/build/q-ZpnogAZH.js       0.32 kB
server/@qwik-router-config2.js   0.39 kB
server/build/q-B4_kJgcT.js       0.40 kB
server/entry.ssr.js             50.22 kB
server/build/q-BvMHAeyE.js      86.61 kB
✓ built in 537ms

Starting Qwik Router SSG...
QWIK ERROR Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22 _run Error: Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22
    at Fn (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191)
    at Hr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:122)
    at M (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:708)
    at yr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:4533)
    at i (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:109)
    at dr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:266)
    at $r (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:42008)
    at bi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:41834)
    at yi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:39897)
    at file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:38892

!!! /: Error during SSG
Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22
  Pathname: /
  Plugin: qwik-ssg
  File: /D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191
      at Fn (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191)
      at Hr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:122)
      at M (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:708)
      at yr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:4533)
      at i (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:109)
      at dr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:266)
      at $r (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:42008)
      at bi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:41834)
      at yi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:39897)
      at file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:38892
dist\index.html
QWIK ERROR Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22 _run Error: Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22
    at Fn (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191)
    at Hr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:122)
    at M (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:708)
    at yr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:4533)
    at i (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:109)
    at dr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:266)
    at $r (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:42008)
    at bi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:41834)
    at yi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:39897)
    at file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:38892

!!! /apple/: Error during SSG
Code(Q14) https://github.com/QwikDev/qwik/blob/main/packages/qwik/src/core/error/error.ts#L22
  Pathname: /apple/
  Plugin: qwik-ssg
  File: /D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191
      at Fn (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:191)
      at Hr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:122)
      at M (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:708)
      at yr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:4533)
      at i (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:109)
      at dr (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:8:266)
      at $r (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:42008)
      at bi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:41834)
      at yi (file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:39897)
      at file:///D:/Project/qwik-app/server/build/q-BvMHAeyE.js:7:38892
dist\apple\index.html
error during build:
undefined
```

</details>

**Comment by mapp113** [comment]
I ran the build command again, the error is same as first i post.

No idea how to reproduce these

> This is my console look like

**Comment by maiieul** [comment]
@mapp113 thanks. This looks like a different error/issue. Are you able to run `npm run dev` and `npm run preview`?

**Comment by mapp113** [comment]
@maiieul yes, `npm run dev` and `npm run preview` works fine.

**Comment by maiieul** [comment]
So I assume the original error is fixed in V2. Perhaps you can try to remove your static adapter code, and run the `npx qwik add static` again to solve this issue.

**Comment by mapp113** [comment]
no, even i created a new project in v2, add static but cant `npm run build.server`. Now the console is look like the last i post

**Comment by maiieul** [comment]
@mapp113 can you try install the pkg.pr.new in your project: https://github.com/QwikDev/qwik/pull/8040#issuecomment-3377730832 ?

This might have fixed your issue.

**Comment by mapp113** [comment]
@maiieul that package still doesn’t fix it, and v1.17.0 has the same problem.

**Comment by maiieul** [comment]
Reopening since the fix PR got reverted

**Comment by maiieul** [comment]
@mapp113 It should work on V2 latest. Can you try it out? 

This is the hash: https://pkg.pr.new/QwikDev/qwik/@qwik.dev/core@4827d2e

**Comment by mapp113** [comment]
@maiieul With your provided package, npm `run build.server` still has bugs. But if I run `build` and then `build.server`, the success rate is about 50/50.

**Comment by Varixo** [comment]
should be solved by #8110. At least it works on my Windows machine and CI. Feel free to reopen if needed.

**Comment by thejackshelton** [comment]
@mapp113 can you try 1.17.2 and let us know if you still run into this issue
